version: '3.1'

services:
  web:
    image: odoo:18.0
    ports:
      - "8069:8069"
    volumes:
      - ./addons_custom:/mnt/extra-addons
    environment:
      - DB_HOST=${RAILWAY_PRIVATE_DOMAIN}         
      - DB_PORT=5432                             
      - DB_USER=${PGUSER}                        
      - DB_PASSWORD=${POSTGRES_PASSWORD}         
      - DB_NAME=${PGDATABASE}                    
      - ADDONS_PATH=/mnt/extra-addons             
    depends_on:
      - db  

volumes:
  db_data:
  
